### ISSUE TITLE
Add virtual joystick support

### ISSUE THREAD

**Issue by ne0fhyk** [DroidPlanner/Tower#1432]
More details to be added...

**Comment by Loop-Zilla** [comment]
ne0fhyk, 

I agree.  At least bring back what was commented out in DroidPlanner.  If this feature is too risky for aerial assets, bring it in only for rovers and/or gimbal control.  I don't use an RC Tx anymore with our rovers, but the ability to back out of a corner with the virtual joysticks would be great.

**Comment by Linjieqiang** [comment]
great!

**Comment by rmackay9** [comment]
I would really like it if we didn't use rc-overrides for this but instead used one of these alternative mavlink messages:
http://mavlink.org/messages/common#SET_ATTITUDE_TARGET
http://mavlink.org/messages/common#SET_POSITION_TARGET_LOCAL_NED
This would require a little work on the arducopter side to grab and interpret these messages while in Guided mode but longer-term I think it would be simpler and easier because it avoids muddling RC controlled modes (Stabilize, Loiter, etc) and tablet controlled modes (Guided, Auto).

**Comment by ne0fhyk** [comment]
@rmackay9 That's the option Chris and I are leaning toward since it avoids the possible issues associated with RC Overrides.
Along the messages you mentioned, couldn't [`SET_POSITION_TARGET_GLOBAL_INT`](http://mavlink.org/messages/common#SET_POSITION_TARGET_GLOBAL_INT) be used as well?

**Comment by billbonney** [comment]
You might want to consider this message as well http://mavlink.org/messages/common#MANUAL_CONTROL
Not only does it offer the x,y,z,r controls, it offers a set of 16 push buttons as related to a joystick

**Comment by R-Lefebvre** [comment]
That would be great, as it would also move us on another issue which is to enable Aux Functions from the tablet.

**Comment by rimb05** [comment]
I think having the ability to touch a virtual joystick to deviate from a guided or auto course would be great. When the user lets go of the joystick, guided/auto mode should resume.   I don't think there's much risk as long as joystick mode works like FBWB while its flying under joystick control. 

If possible, having the ability to only activate one axis of the joystick (horizontal, for example) would make it very safe, as it would only allow course deviations.

**Comment by ne0fhyk** [comment]
Replaced by #1518
