### ISSUE TITLE
Tower Will not arm.

### ISSUE THREAD

**Issue by rogerhogan** [DroidPlanner/Tower#1785]
Everything is normal until It is time to hit "arm" and then I swipe the arrow to the right, at this time I get the words: sorry tower has stopped.
I am using:

Galaxy Tab A
Android Version 6.0.1
3DR Services v1.6.0 beta 2
Tower v3.2.1

roger
roger@railroadsusa.com

**Comment by franknitty69** [comment]
confirmed.

galaxy tab s
android lollipop 5.0.2
3DR Services v1.6.0 beta 2
Tower v3.2.1

**Comment by ne0fhyk** [comment]
@rogerhogan @franknitty69 The issue was caused because 3DR pushed a buggy version of 3DR Services (v1.6+).

It should go away if you revert to version 1.5.3 which can be found at https://github.com/dronekit/dronekit-android/releases/download/3DRServices-v1.5.3.4/3dr-services-prod-release.105304.apk

We're working to remove the dependency between Tower and 3DR Services to prevent such issues in the future.

**Comment by rogerhogan** [comment]
Thank You very much. I will try that today.



Fredia Huya-Kouadio wrote:

**Comment by rogerhogan** [comment]
I did as instructed and every is back to working again. Thank You , Thank You for the help.
